config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#new'
  get 'contacts', to: 'contacts#new'
  post 'contacts', to: 'contacts#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :email,
        presence: true, uniqueness: true,
        format: { with: URI::MailTo::EMAIL_REGEXP } 
    validates :first_name,
        presence: true, length: {maximum: 30}
    validates :last_name,
        presence: true, length: {maximum: 30}
    validates :message,
        presence: true, length: {minimum: 10, maximum: 500}
    validates :phone,
        numericality: true,
        allow_nil: true,
        allow_blank: true,
        length: { :minimum => 10, :maximum => 15 }


    after_create do
        ContactMailer.new_contact(self.id).deliver_now
    end
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
        query_locale = params[:locale]
        valid_locale = I18n.available_locales.map(&:to_s).include?(query_locale)
        if valid_locale
          I18n.locale = query_locale
        else
          I18n.locale = I18n.default_locale
        end
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to contacts_url, notice: t('messages.contact_create_success')  }
        format.json { render json: @contact, status: :created, notice: t('messages.contact_create_success') }
      else
        format.html { render :new, notice:  t('messages.contact_create_fail')}
        format.json { render json: @contact.errors, status: :unprocessable_entity, notice: t('messages.contact_create_fail') }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%# Language Selector %>


<%# Form %>
<div class="m-10-per">
  <%= form_with(model: contact, url: "/contacts?locale=#{I18n.locale}" ,local: true) do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= form.label t('form.field_labels.first_name') %>
      <%= form.text_field :first_name, placeholder: t('form.field_placeholders.first_name') %>
      <span class="required">*</span>
    </div>

    <div class="field">
      <%= form.label t('form.field_labels.last_name') %>
      <%= form.text_field :last_name, placeholder: t('form.field_placeholders.last_name') %>
      <span class="required" >*</span>
    </div>

    <div class="field">
      <%= form.label t('form.field_labels.email') %>
      <%= form.text_field :email, placeholder: t('form.field_placeholders.email') %>
      <span class="required">*</span>
    </div>

    <div class="field">
      <%= form.label t('form.field_labels.phone') %>
      <%= form.text_field :phone, placeholder: t('form.field_placeholders.phone') %>
    </div>

    <div class="field">
      <%= form.label t('form.field_labels.message') %>
      <%= form.text_area :message, cols: 30, rows: 10, placeholder: t('form.field_placeholders.message')  %>
      <span class="required">*</span>
    </div>

    <div class="actions">
      <%= form.submit t('form.submit') %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div id="language_selector" class="pull-right">
  <% I18n.available_locales.each do |code|%>
    <%= link_to code, "/contacts?locale=#{code}", class: code == I18n.locale ? 'active': '' %> |
  <%end%>
</div>

<h1> <%= t('form.header') %></h1>

<h5 class="green"><%= notice %></h5>

<%= render 'form', contact: @contact %>

<%= link_to  t('form.back'), contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactForm2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>